"""add invoice events relation

Revision ID: 4204d5d9cc4c
Revises: 71d710cf71fc
Create Date: 2024-02-24 12:18:44.959708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4204d5d9cc4c'
down_revision: Union[str, None] = '71d710cf71fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dian_invoice_events',
    sa.Column('invoice_id', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['DianEvent.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['DianInvoice.id'], )
    )
    op.drop_table('invoice_events')
    op.drop_constraint('DianEvent_ibfk_1', 'DianEvent', type_='foreignkey')
    op.drop_column('DianEvent', 'invoice_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('DianEvent', sa.Column('invoice_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('DianEvent_ibfk_1', 'DianEvent', 'DianInvoice', ['invoice_id'], ['id'])
    op.create_table('invoice_events',
    sa.Column('dian_event_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('dian_invoice_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['dian_event_id'], ['DianEvent.id'], name='invoice_events_ibfk_1'),
    sa.ForeignKeyConstraint(['dian_invoice_id'], ['DianInvoice.id'], name='invoice_events_ibfk_2'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('dian_invoice_events')
    # ### end Alembic commands ###
