"""empty message

Revision ID: e8f8db0058b3
Revises: 
Create Date: 2024-02-24 10:37:50.162047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8f8db0058b3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('DianEntity',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('nit', sa.String(length=10), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('DianInvoice',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('cufe', sa.String(length=100), nullable=True),
    sa.Column('graphic_link', sa.String(length=100), nullable=True),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.Column('iva', sa.Integer(), nullable=True),
    sa.Column('serie', sa.String(length=10), nullable=True),
    sa.Column('folio', sa.String(length=10), nullable=True),
    sa.Column('issue_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('receiver_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['receiver_id'], ['DianEntity.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['DianEntity.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('DianEvent',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('code', sa.String(length=10), nullable=True),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('invoice_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['DianInvoice.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('DianEvent')
    op.drop_table('DianInvoice')
    op.drop_table('DianEntity')
    # ### end Alembic commands ###
